from __future__ import annotations

"""Dependency-light browser shell for the two retained workflow products."""

from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


PAGE = r"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Banking Verification & Dormancy AI</title>
<style>:root{--navy:#173d62;--blue:#1769b3;--green:#86bc25;--purple:#6657f5;--amber:#ffb600;--bg:#f4f6f8;--ink:#152536}*{box-sizing:border-box}body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:var(--bg);color:var(--ink)}aside{position:fixed;inset:0 auto 0 0;width:260px;background:var(--navy);color:#fff;padding:25px 20px}.brand{display:flex;gap:12px;align-items:center;padding-bottom:22px;border-bottom:1px solid #ffffff24}.mark{display:grid;place-items:center;width:40px;height:40px;border-radius:12px;background:var(--green);color:var(--navy);font-weight:900}.brand small{display:block;color:#bfd0e0}.nav{display:grid;gap:8px;margin-top:24px}.nav button{background:transparent;text-align:left;color:#dce8f2;border:0}.nav button.active,.nav button:hover{background:#ffffff18}.scope{position:absolute;bottom:24px;left:20px;right:20px;padding:14px;border-radius:14px;background:#0d2d4c;font-size:.82rem;color:#bfd0e0}main{margin-left:260px;padding:30px 44px}header{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid #d9e0e7;padding-bottom:20px}h1{margin:4px 0;color:var(--blue)}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:.72rem;font-weight:800;color:#66788a}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin-top:20px}.card{background:#fff;border-radius:16px;padding:23px;box-shadow:0 7px 24px #173d6210}.card h2{margin-top:0;color:var(--navy)}label{display:grid;gap:6px;font-weight:650;margin-top:10px}input,select,textarea,button{width:100%;padding:11px 12px;border:1px solid #ccd6e0;border-radius:10px;font:inherit}textarea{min-height:110px}button{background:var(--blue);color:#fff;border:0;font-weight:700;cursor:pointer}.secondary{background:#fff;color:var(--navy);border:1px solid #ccd6e0}.result{white-space:pre-wrap;max-height:430px;overflow:auto;background:#f7f9fb;padding:14px;border-radius:12px;font:12px Consolas,monospace}.hidden{display:none}.notice{padding:12px;border-radius:10px;background:#e8e5ff;color:#4034a5}.login{max-width:520px;margin:7vh auto}.login aside{position:static;width:auto;border-radius:20px}.login main{margin:0;padding:20px}@media(max-width:850px){aside{position:static;width:auto}.scope{display:none}main{margin:0;padding:20px}.grid{grid-template-columns:1fr}.nav{display:flex;overflow:auto}.nav button{white-space:nowrap}}</style></head>
<body><section id="login" class="login"><aside><div class="brand"><span class="mark">B</span><div><b>Banking Verification AI</b><small>Human-controlled operations</small></div></div></aside><main class="card"><h1>Sign in</h1><label>Role<select id="role"><option>CUSTOMER</option><option>UNDERWRITER</option><option>COMPLIANCE</option><option>ADMIN</option></select></label><label>Username<input id="username" value="customer"></label><label>Password<input id="password" type="password" value="customer123"></label><button onclick="login()">Sign in</button><p id="loginError"></p></main></section>
<section id="app" class="hidden"><aside><div class="brand"><span class="mark">B</span><div><b>Verification AI</b><small>Bank statements & dormancy</small></div></div><div class="nav"><button class="active" onclick="show('overview',this)">Overview</button><button onclick="show('statements',this)">Bank Statements</button><button onclick="show('dormancy',this)">Dormancy</button><button onclick="show('approvals',this)">Approvals</button></div><div class="scope">Only two retained products<br>• Income verification<br>• Dormancy & escheatment</div></aside><main><header><div><span class="eyebrow">Agentic AI · bounded autonomy</span><h1 id="pageTitle">Operations Overview</h1><div id="identity"></div></div><button class="secondary" style="width:auto" onclick="location.reload()">Sign out</button></header>
<div id="overview" class="view"><div class="grid"><article class="card"><h2>Bank Statement & AA Verification</h2><p>Upload PDF/JPG statements, submit extracted transactions, calculate explainable cash-flow and income insights, and cross-check ITR/GST values.</p></article><article class="card"><h2>Dormant Account Lifecycle</h2><p>Detect, re-engage, track clocks, prepare transfers, enforce maker-checker, support reclaim, pause automation, and export evidence.</p></article><article class="card notice"><b>Human authority retained</b><p>Risk insights do not approve lending. Classification, transfer, reactivation and claim payout remain governed.</p></article><article class="card"><h2>Integration boundary</h2><p>CBS, GL, V-CIP, communication gateways, e-Kuber and UDGAM are simulated/provider boundaries until certified adapters are installed.</p></article></div></div>
<div id="statements" class="view hidden"><div class="grid"><article class="card"><h2>Upload financial documents</h2><form id="uploadForm"><label>Document type<select name="document_type"><option>BANK_STATEMENT</option><option>ITR</option><option>GST</option></select></label><label>PDF password (if protected)<input name="password" type="password"></label><label>Files<input name="files" type="file" accept=".pdf,.jpg,.jpeg" multiple required></label><button>Upload</button></form></article><article class="card"><h2>Analyze extracted transactions</h2><p>Paste the API JSON contract for header, consent/AA evidence and transactions.</p><textarea id="analysisPayload" placeholder='{"customer_id":"CUST-1","header":{...},"transactions":[...],"evidence":{...}}'></textarea><button onclick="analyze()">Run explainable analysis</button></article><article class="card" style="grid-column:1/-1"><h2>Result</h2><pre id="statementResult" class="result">No request yet.</pre></article></div></div>
<div id="dormancy" class="view hidden"><div class="grid"><article class="card"><h2>Run lifecycle</h2><label>Lifecycle JSON<textarea id="dormancyPayload">{"account_id":"ACC-100","customer_id":"CUST-1","jurisdiction":"IN-RBI-DEA","balance":1000,"last_customer_activity":"2016-01-01","as_of_date":"2026-01-01"}</textarea></label><button onclick="call('/dormancy/cycles','POST','dormancyPayload','dormancyResult')">Run lifecycle</button></article><article class="card"><h2>Deadline alerts</h2><label>As of date<input id="alertDate" type="date"></label><label>Window days<input id="alertDays" type="number" value="90"></label><button onclick="alerts()">Load alerts</button></article><article class="card" style="grid-column:1/-1"><h2>Lifecycle result</h2><pre id="dormancyResult" class="result">No request yet.</pre></article></div></div>
<div id="approvals" class="view hidden"><div class="grid"><article class="card"><h2>Approval queue</h2><button onclick="call('/approvals','GET',null,'approvalResult')">Refresh</button><pre id="approvalResult" class="result">No request yet.</pre></article><article class="card"><h2>Maker-checker decision</h2><label>Approval ID<input id="approvalId"></label><label>Decision<select id="decision"><option>APPROVED</option><option>REJECTED</option></select></label><label>Note<input id="decisionNote"></label><button onclick="decision()">Submit decision</button></article></div></div>
</main></section><script>const API='http://127.0.0.1:8001/api/v1';let token='',role='';async function request(path,options={}){options.headers=Object.assign({'Authorization':'Bearer '+token},options.headers||{});const r=await fetch(API+path,options),body=await r.json();if(!r.ok)throw new Error(body.detail||body.title||'Request failed');return body}async function login(){try{role=document.getElementById('role').value;const body=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:username.value,password:password.value,user_type:role})}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.detail);return x});token=body.data.accessToken;identity.textContent=body.data.user.display_name+' · '+role;document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden')}catch(e){loginError.textContent=e.message}}function show(id,b){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');pageTitle.textContent=b.textContent}async function call(path,method,payloadId,resultId){try{const options={method};if(payloadId){options.headers={'Content-Type':'application/json'};options.body=document.getElementById(payloadId).value}const x=await request(path,options);document.getElementById(resultId).textContent=JSON.stringify(x.data,null,2)}catch(e){document.getElementById(resultId).textContent='Error: '+e.message}}uploadForm.onsubmit=async e=>{e.preventDefault();try{const x=await request('/financial-documents',{method:'POST',body:new FormData(uploadForm)});statementResult.textContent=JSON.stringify(x.data,null,2)}catch(e){statementResult.textContent='Error: '+e.message}};async function analyze(){call('/bank-statement-analyses','POST','analysisPayload','statementResult')}async function alerts(){call('/dormancy/deadline-alerts?as_of_date='+alertDate.value+'&within_days='+alertDays.value,'GET',null,'dormancyResult')}async function decision(){try{const x=await request('/approvals/'+approvalId.value+'/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision:document.getElementById('decision').value,note:decisionNote.value})});approvalResult.textContent=JSON.stringify(x.data,null,2)}catch(e){approvalResult.textContent='Error: '+e.message}}</script></body></html>"""


class Handler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:  # noqa: N802
        if self.path not in {"/", "/index.html"}:
            self.send_error(404); return
        data = PAGE.encode("utf-8")
        self.send_response(200); self.send_header("Content-Type", "text/html; charset=utf-8"); self.send_header("Content-Length", str(len(data))); self.end_headers(); self.wfile.write(data)

    def log_message(self, format: str, *args: object) -> None:
        return


def run(host: str = "127.0.0.1", port: int = 8000) -> None:
    print(f"Banking Verification UI running at http://{host}:{port}")
    ThreadingHTTPServer((host, port), Handler).serve_forever()


if __name__ == "__main__":
    run()
